### PR TITLE
syntax: support triple-backtick raw blocks.

### PR DESCRIPTION
**Pull request by mikemcquaid**
These are used widely on e.g. GitHub for syntax highlighted blocks.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@infininight @sanssecours @sorbits Any thoughts on this? Thanks!

**Comment by infininight** [comment]
This is a duplicate of #9, #13, #15, #32 and #36; see there for more information on the reasoning.

**Comment by mikemcquaid** [comment]
@infininight Thanks for the pointers.

**Comment by mikemcquaid** [comment]
In case anyone finds this: I created my own TextMate bundle for that https://github.com/mikemcquaid/GitHub-Markdown.tmbundle

**Comment by MikeMcQuaid** [comment]
My repository is now part of TextMate 2:  see the Markdown (GitHub) bundle under "Bundles".

**Pull request closed without merging**
