### PR TITLE
Allow raw_block to support ```

### PR DESCRIPTION
**Pull request by huacnlee**
Allow raw block to support \`\`\` like GitHub

    ```ruby
    # comment line
    class Foo
      def bar
      end
    end
    ```

### CODE REVIEW

**Comment by mmzoo** [comment]
Oh, that would be wonderful. Without this, the

```ruby
# comment line
```

in the example provided above is interpreted as a 

### huge headline

even though it's supposed to be part of the source code

**Comment by infininight** [comment]
The goal of this bundle/grammar is to implement the core markdown spec, we will not be adding the features of any of the various variants/forks. These would be best implemented as a new grammar or an injected grammar.

**Comment by mmzoo** [comment]
@infininight Thank you for your response, makes sense to me.

Ah, look [at that](https://github.com/streeter/markdown-redcarpet.tmbundle)!

**Comment by MikeMcQuaid** [comment]
TextMate 2 now has a Markdown (GitHub) bundle under "Bundles" that I think may address many of the folks' desires here (repository for the curious: https://github.com/MikeMcQuaid/GitHub-Markdown.tmbundle).

**Pull request closed without merging**
