### PR TITLE
Secondary support for Multimarkdown?

### PR DESCRIPTION
**Pull request by napaxton**
Fletcher Penny's multimarkdown bundle has good extra functionality for those of use who use MMD. Unfortunately, it's a number of commits different than the main MD bundle these days. 

What are the options for getting Fletcher's work integrated into the MD bundle? Or, alternately, how can we provide a second bundle that uses the latest work on the main MD bundle but which also uses Penney's additional features that take advantage of MMD?

### CODE REVIEW

**Comment by feekApp** [comment]
an updated, integrated and maintained version of Fletcher Penny's MMD in the default TM-MD bundle would be great!

== feek

**Comment by infininight** [comment]
Won't be pulling this in, we want to keep the main bundle as supporting the base version of markdown. Extensions to markdown need to be handled in secondary bundles that either provide a separate grammar or inject new rules into the standard grammar. This alternative bundle has never been available in the installer because it conflicted with the base bundle, so to be accepted it would be good if someone could update it to resolve those conflicts. Then I'd be happy to add it to the list of installable bundles.

A good example of a markdown bundle in this vein is the Markdown (Github) bundle.

**Comment by napaxton** [comment]
I don't know Python, but I will try to learn enough git here to try to merge the fletcher changes with the current MD bundle. 

Any resources on dealing with the two forks and how to bring them together would be appreciated!

**Comment by sorbits** [comment]
I don’t think this is about Python as much as figuring out what actually needs to be “merged” from the MMD bundle, for example, the MMD bundle seems to have its own preview command, but if the goal is to just use `multimarkdown` as processor, then set `TM_MARKDOWN` to `/path/to/multimarkdown` and the standard bundle’s commands will use `multimarkdown` to do the processing (that’s what I use here).

**Comment by napaxton** [comment]
What's the best way to message about this? Should I fork the official bundle[^ I've already forked and played with the Fletcher bundle] and open a discussion?

**Comment by sorbits** [comment]
If you want to solicit feedback, the best place is probably the [TextMate mailing list](http://lists.macromates.com/listinfo/textmate).

**Pull request closed without merging**
